### ISSUE TITLE
Add hooks for more user code

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/bashly#116]
It would be nice to have the ability to allow user to inject code (similar to how the `initialize.sh` behaves) in more places, for example:

- The very top of the bash script (solves #114) - this will also be a good way to let people *replace* the default header if they want to.
- Before the call to any user function (solves #113)
- After the call to any user function

So the execution order might look like this:

1. `header` (user injectable)
2. `initialize` (user injectable)
3. *other bashly code*
4. `before` (user injectable)
5. *user code*
6. `after` (user injectable)

### TODO

- [x] Custom header (#120)
- [x] Decide if any additional hooks are needed:
  - [ ] Hook for "before user code"
  - [ ] Hook for "after user code"

_Originally posted in https://github.com/DannyBen/bashly/issues/113#issuecomment-932493851_

**Comment by wolfgang42** [comment]
Hm, I wasn't expecting `header.sh` to *replace* the contents of the existing header, though in hindsight I think that makes sense. This does seem to satisfy my needs for the version check.

**Comment by DannyBen** [comment]
Closing this, since #148 solves the reasons that this issue was open in the first place.

I do not see a strong enough use case for this. If there is one, we can reevaluate.
